### ISSUE TITLE
Directory listing fails

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.viervijfzes#104]
Kodi (19.3 (19.3.0) Git:19.3-Matrix). 
Running on LibreELEC (official): 10.0.1, kernel: Linux x86 64-bit version 5.10.76
GoPLay 0.4.7-Matrix

Error when loading "Mijn lijst" or searching for a series.
Steps: 
1. open GoPlay, authentication OK
2. see what's on "Mijn lijst" OK
3. Select a series from 'Mijn Lijst' to see episodes --> TypeError: an integer is required (got type str)

> 2022-07-04 21:34:19.031 T:4166     INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
> 2022-07-04 21:34:20.669 T:4166     INFO <general>: initializing python engine.
> 2022-07-04 21:34:21.077 T:4166    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: an integer is required (got type str)
>                                                    Traceback (most recent call last):
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
>                                                        run(argv)
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 194, in run
>                                                        routing.run(params)
>                                                      File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
>                                                        self._dispatch(self.path)
>                                                      File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
>                                                        view_func(**kwargs)
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 74, in show_catalog_program
>                                                        Catalog().show_program(program)
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/catalog.py", line 62, in show_program
>                                                        program = self._api.get_program(program_id, extract_clips=True, cache=CACHE_PREVENT)  # Use CACHE_PREVENT since we want fresh data
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 257, in get_program
>                                                        program = self._parse_program_data(data)
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 653, in _parse_program_data
>                                                        program.episodes = [
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 654, in <listcomp>
>                                                        ContentApi._parse_episode_data(episode, playlist.get('id'))
>                                                      File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 692, in _parse_episode_data
>                                                        aired=datetime.fromtimestamp(data.get('createdDate')),
>                                                    TypeError: an integer is required (got type str)
>                                                    -->End of Python script error report<--
>                                                    
> 2022-07-04 21:34:21.436 T:4166     INFO <general>: Python interpreter stopped
> 2022-07-04 21:34:21.439 T:4169     INFO <general>: Skipped 1 duplicate messages..
> 2022-07-04 21:34:21.439 T:4169    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.viervijfzes/catalog/nonkels
> 2022-07-04 21:34:21.458 T:820     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viervijfzes/catalog/nonkels) failed

**Comment by M0nty99** [comment]
I'm facing the same issue, on the same version of libreelec. In addition also having issues with playback, getting a random Goplay error, check the logs for more information. Will upload logs later

**Comment by ghetom** [comment]
As a temporary workaround I placed the error line in comment.

Try this:
1. Download the zip from github and extract to folder 'plugin.video.viervijfzes-master'
2. Navigate to plugin.video.viervijfzes-master/resources/lib/viervijfzes
3. Open content.py
4. Place # at the beginning of line 692: #aired=datetime.fromtimestamp(data.get('createdDate')),
5. Compress the folder 'plugin.video.viervijfzes-master' to zip again
6. Uninstall the addon from repository and install this zip in kodi
7. Log in again

Didn't test everything but this worked for me.

**Comment by michaelarnauts** [comment]
@badoneti, @M0nty99 or @ghetom can you try with this version?

[plugin.video.viervijfzes-0.4.7.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/9064214/plugin.video.viervijfzes-0.4.7.zip)
[plugin.video.viervijfzes-0.4.7+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/9064215/plugin.video.viervijfzes-0.4.7%2Bmatrix.1.zip)

The problem was that `data.get('createdDate')` suddenly didn't return an integer anymore, but a string. This was due to a change at GoPlay.

**Comment by michaelarnauts** [comment]
> @michaelarnauts this fixes the issue, tested with matrix version included above

Thanks for verifying! I'll make a v0.4.8 release today.

**Comment by ghetom** [comment]
The matrix version works indeed. Thanks!
