### ISSUE TITLE
No episode_program found errors

### ISSUE THREAD

**Issue by dJos1991** [add-ons/plugin.video.viervijfzes#112]
**Describe the bug**
Since today, no episode is starting from the GoPlay plugin. In the logs are a few lines about 'found no episode_program' and at the end there is also an error like: "Authorization header requires 'Credential' parameter... (I replaced the Authorization code with some X's)

**To Reproduce**
1. Start any program in this GoPlay addon
2.
3.

**Expected behavior**
/

**Screenshots**
/

**Logs**
```
2023-01-12 22:14:02.198 T:3404     INFO <general>: initializing python engine.
2023-01-12 22:14:02.589 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.auth] We could not use the cache since it is invalid or non-existent.
2023-01-12 22:14:04.064 T:3404  WARNING <general>: Invalid media type ""
2023-01-12 22:14:04.069 T:3404     INFO <general>: Skipped 9 duplicate messages..
2023-01-12 22:14:04.069 T:3404     INFO <general>: CPythonInvoker(5, C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py): script successfully run
2023-01-12 22:14:11.210 T:3404     INFO <general>: initializing python engine.
2023-01-12 22:14:11.477 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for Bewoners ontdekken nieuwe ruimte in Big Brother-huis: "Dit is mijn secret room."
2023-01-12 22:14:11.477 T:3404  WARNING <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.477 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for De spanningen lopen hoog op in Big Brother: "Van mijn roze wolk afgestampt"
2023-01-12 22:14:11.478 T:3404  WARNING <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.478 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for Dag 2 in Big brother en Michelangelo heeft het meteen moeilijk: “Hoe lang nog?"
2023-01-12 22:14:11.478 T:3404  WARNING <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.478 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for Opvallende uitspraak in Big Brother: "Ik kreeg een lapdance van Justin Bieber"
2023-01-12 22:14:11.478 T:3404  WARNING <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.478 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for Zo gaat Big Brother van start: "Ohnee, dat is direct een zware opdracht." 
2023-01-12 22:14:11.479 T:3404  WARNING <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.479 T:3404  WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Found no episode_program for Big Brother gaat 9 januari van start
2023-01-12 22:14:11.493 T:3404     INFO <general>: Skipped 1 duplicate messages..
2023-01-12 22:14:11.493 T:3404     INFO <general>: CPythonInvoker(5, C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py): script successfully run
2023-01-12 22:14:13.164 T:3404     INFO <general>: initializing python engine.
2023-01-12 22:14:13.260 T:3404     INFO <general>: CPythonInvoker(5, C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py): script successfully run
2023-01-12 22:14:17.833 T:3404     INFO <general>: initializing python engine.
2023-01-12 22:14:18.005 T:3404    ERROR <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=eyJraWQiOiJCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXeW49KjK-w"}
2023-01-12 22:14:18.015 T:3404    ERROR <general>: Skipped 3 duplicate messages..
2023-01-12 22:14:18.015 T:3404    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 194, in run
                                                       routing.run(params)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 167, in play_catalog
                                                       Player().play(uuid)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 107, in play
                                                       resolved_stream = self._resolve_stream(uuid)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 138, in _resolve_stream
                                                       resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 357, in get_stream_by_uuid
                                                       response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
                                                     File "C:\Users\samge\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 737, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
                                                   -->End of Python script error report<--
                                                   
2023-01-12 22:14:18.086 T:3404     INFO <general>: Python interpreter stopped
2023-01-12 22:14:18.101 T:3740    ERROR <general>: Skipped 3 duplicate messages..
2023-01-12 22:14:18.101 T:3740    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.viervijfzes/play/catalog/45be285a-cc4b-4d62-b7e9-208c2a9959cf]
```

**System**
 - Addon version: 0.4.9
 - Kodi version: 19.5.0
 - Inputstream adaptive version: 0.5.10
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Windows and Android TV
 - Special Hardware (RPI / Vero4K+ / ...): Laptop and Mi Box S

**Additional context**
/

**Comment by mediaminister** [comment]
I made a quick fix. Please test:
Kodi 18: [plugin.video.viervijfzes-0.4.9.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/10406380/plugin.video.viervijfzes-0.4.9.zip)
Kodi 19/20: [plugin.video.viervijfzes-0.4.9+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/10406382/plugin.video.viervijfzes-0.4.9%2Bmatrix.1.zip)

**Comment by aGreatDay** [comment]
Tested and fixes #113 for me, but loading 'my list' gives an error

**Comment by mediaminister** [comment]
Fixed my list:
Kodi 18: [plugin.video.viervijfzes-0.4.9.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/10406722/plugin.video.viervijfzes-0.4.9.zip)
Kodi 19/20: [plugin.video.viervijfzes-0.4.9+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/10406723/plugin.video.viervijfzes-0.4.9%2Bmatrix.1.zip)

**Comment by aGreatDay** [comment]
Thanks, 'my list' works now too!

**Comment by dJos1991** [comment]
Thanks for the quick fix, everything is working fine now!

**Comment by M0nty99** [comment]
Had the same issue with playback, installed the fix and everything is working again. Thanks for the quick fix!
Much appreciated!

**Comment by alfaajx732** [comment]
Great works again, many thanks for the fix

**Comment by petervmokfbde** [comment]
hello

how do i install this on a tv?
