### ISSUE TITLE
Error when loading any video

### ISSUE THREAD

**Issue by aGreatDay** [add-ons/plugin.video.viervijfzes#113]
Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 194, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 167, in play_catalog
                                                       Player().play(uuid)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 107, in play
                                                       resolved_stream = self._resolve_stream(uuid)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 138, in _resolve_stream
                                                       resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 357, in get_stream_by_uuid
                                                       response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 737, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
```

**Comment by michaelarnauts** [comment]
Quite sure that this is fixed in the branch of mediaminister. I've merged it now.

Please try this zip: https://github.com/add-ons/plugin.video.viervijfzes/archive/refs/heads/master.zip
