### ISSUE TITLE
Authorization header requires 'Credential' parameter

### ISSUE THREAD

**Issue by StevenDeRoover** [add-ons/plugin.video.viervijfzes#115]
Since yesterday, I get an error while trying to start an episode.  The error log states "Authorization header requires 'Credential' parameter".  Maybe GoPlay changed something?

**Comment by StevenDeRoover** [comment]
I don't think this issue is closed, and I'm not sure if it's a duplicate of #122.

I still have the same issue, with v0.4.9-matrix.1.

2023-01-15 14:27:43.219 T:12340    INFO <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] Starting new HTTPS connection (1): api.viervijfzes.be:443
2023-01-15 14:27:43.371 T:12340    INFO <general>: Skipped 4 duplicate messages..
2023-01-15 14:27:43.371 T:12340    INFO <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] https://api.viervijfzes.be:443 "GET /content/2580b3f8-c0e6-4436-a1fa-0f643a80d06c HTTP/1.1" 403 1881
2023-01-15 14:27:43.372 T:12340   ERROR <general>: Skipped 4 duplicate messages..
2023-01-15 14:27:43.372 T:12340   ERROR <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=<jwttoken>"}
2023-01-15 14:27:43.378 T:12340   ERROR <general>: Skipped 4 duplicate messages..
2023-01-15 14:27:43.378 T:12340   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 194, in run
                                                       routing.run(params)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 167, in play_catalog
                                                       Player().play(uuid)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 107, in play
                                                       resolved_stream = self._resolve_stream(uuid)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 138, in _resolve_stream
                                                       resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 357, in get_stream_by_uuid
                                                       response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
                                                     File "C:\Users\steve\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 737, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
                                                   -->End of Python script error report<--

**Comment by michaelarnauts** [comment]
Quite sure that this is fixed in the branch of mediaminister. I've merged it now.

Please try this zip: https://github.com/add-ons/plugin.video.viervijfzes/archive/refs/heads/master.zip

**Comment by StevenDeRoover** [comment]
This fixes the problem. Thanks!
