### ISSUE TITLE
kodi : goplay does not work anymore : Python Exception: Could not fetch data

### ISSUE THREAD

**Issue by pborreke** [add-ons/plugin.video.viervijfzes#116]
The plugin worked fine for a few month's, but since a few weeks it doesn't.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 194, in run
                                                       routing.run(params)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 167, in play_catalog
                                                       Player().play(uuid)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 107, in play
                                                       resolved_stream = self._resolve_stream(uuid)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 138, in _resolve_stream
                                                       resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 357, in get_stream_by_uuid
                                                       response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
                                                     File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 737, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
                                                   -->End of Python script error report<--

**Comment by PeterCloet** [comment]
I noticed the same issue (same error in the logs) since today. Last time, I ran the plug-in was on Friday.

**Comment by peno64** [comment]
Indeed I have the same issue and note that this is with addon version  0.4.9+matrix.1 which is the latest version

**Comment by on4bam** [comment]
I can confirm. LibreELEC (official): 10.0.4 Kodi (19.5 (19.5.0) Git:19.5-Matrix). Platform: Linux ARM 32-bit on Rpi4

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'Exception'>
Error Contents: Could not fetch data
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
  run(argv)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 194, in run
  routing.run(params)
File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
  self._dispatch(self.path)
File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
  view_func(**kwargs)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 174, in play_from_page
  Player().play_from_page(unquote(page))
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 77, in play_from_page
  resolved_stream = self._resolve_stream(episode.uuid)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 138, in _resolve_stream
  resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 357, in get_stream_by_uuid
  response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 737, in _get_url
   raise Exception('Could not fetch data')
Exception: Could not fetch data
-->End of Python script error report<--

**Comment by abanink** [comment]
kodi x86_64 20.0+git20230115.1026-389e701cb9-0~jammy 
goplay add-on version 0.4.9+matrix.1

Debug log:
> 2023-01-16 17:16:45.472 T:36362    info <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.auth] Got an id token from memory
> 2023-01-16 17:16:45.478 T:36362    info <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] Starting new HTTPS connection (1): api.viervijfzes.be:443
> 2023-01-16 17:16:45.913 T:36362    info <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] https://api.viervijfzes.be:443 "GET /content/7723475b-1ec0-43e4-8fd8-08becfb2affe HTTP/1.1" 403 1651
> 2023-01-16 17:16:45.914 T:36362   error <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=eyJraWQ...*redacted*"}
> 2023-01-16 17:16:45.917 T:36362   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'Exception'>
>                                                    Error Contents: Could not fetch data
>                                                    Traceback (most recent call last):
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
>                                                        run(argv)
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 194, in run
>                                                        routing.run(params)
>                                                      File "/home/pascal/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
>                                                        self._dispatch(self.path)
>                                                      File "/home/pascal/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
>                                                        view_func(**kwargs)
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 167, in play_catalog
>                                                        Player().play(uuid)
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 107, in play
>                                                        resolved_stream = self._resolve_stream(uuid)
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 138, in _resolve_stream
>                                                        resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid)
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 357, in get_stream_by_uuid
>                                                        response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token())
>                                                      File "/home/pascal/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 737, in _get_url
>                                                        raise Exception('Could not fetch data')
>                                                    Exception: Could not fetch data
>                                                    -->End of Python script error report<--

Couldn't find an option in the add-on interface to clear the token (even in expert mode).

Hope it helps

**Comment by michaelarnauts** [comment]
Quite sure that this is fixed in the branch of mediaminister. I've merged it now.

Please try this zip: https://github.com/add-ons/plugin.video.viervijfzes/archive/refs/heads/master.zip

**Comment by PeterCloet** [comment]
Tried and tested. It works! Thanks.

**Comment by peno64** [comment]
> Tried and tested. It works! Thanks.

Confirmed

**Comment by JohanHectors** [comment]
yep thanks buddy !

**Comment by on4bam** [comment]
All OK now. Thanks.

**Comment by pborreke** [comment]
> The plugin worked fine for a few month's, but since a few weeks it doesn't.
> 
> ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'Exception'> Error Contents: Could not fetch data Traceback (most recent call last): File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\addon_entry.py", line 18, in run(argv) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 194, in run routing.run(params) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run self._dispatch(self.path) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch view_func(**kwargs) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\addon.py", line 167, in play_catalog Player().play(uuid) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 107, in play resolved_stream = self._resolve_stream(uuid) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\modules\player.py", line 138, in _resolve_stream resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 357, in get_stream_by_uuid response = self._get_url(self.API_VIERVIJFZES + '/content/%s' % uuid, authentication=self._auth.get_token()) File "C:\Users\pborr\AppData\Roaming\Kodi\addons\plugin.video.viervijfzes\resources\lib\viervijfzes\content.py", line 737, in _get_url raise Exception('Could not fetch data') Exception: Could not fetch data -->End of Python script error report<--

**Comment by pborreke** [comment]
Thanks for the succesfully solution in a short period!!
