### ISSUE TITLE
Can't play stream

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.viervijfzes#119]
**Describe the bug**
Can't play Play4 programs

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
2023-02-20 21:37:11.547 T:4836    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPSConnectionPool(host='pubads.g.doubleclick.net', port=443): Max retries exceeded with url: /ondemand/dash/content/2615619/vid/10147806908190527/streams (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xea4f55f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 174, in _new_conn
                                                       conn = connection.create_connection(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 95, in create_connection
                                                       raise err
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 85, in create_connection
                                                       sock.connect(sa)
                                                   ConnectionRefusedError: [Errno 111] Connection refused
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1042, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 358, in connect
                                                       self.sock = conn = self._new_conn()
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 186, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xea4f55f0>: Failed to establish a new connection: [Errno 111] Connection refused
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
                                                       retries = retries.increment(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pubads.g.doubleclick.net', port=443): Max retries exceeded with url: /ondemand/dash/content/2615619/vid/10147806908190527/streams (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xea4f55f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 197, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 170, in play_catalog
                                                       Player().play(uuid, literal_eval(islongform))
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 108, in play
                                                       resolved_stream = self._resolve_stream(uuid, islongform)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/player.py", line 140, in _resolve_stream
                                                       resolved_stream = ContentApi(auth).get_stream_by_uuid(uuid, islongform)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 399, in get_stream_by_uuid
                                                       ad_data = json.loads(self._post_url(url, data=''))
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 766, in _post_url
                                                       response = self._session.post(url, params=params, json=data)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 577, in post
                                                       return self.request('POST', url, data=data, json=json, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 519, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pubads.g.doubleclick.net', port=443): Max retries exceeded with url: /ondemand/dash/content/2615619/vid/10147806908190527/streams (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xea4f55f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   -->End of Python script error report<--

**System**
 - Addon version: v0.4.10
 - Kodi version: 19.4
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec
 - Special Hardware (RPI / Vero4K+ / ...): RPi

**Additional context**

**Comment by michaelarnauts** [comment]
Can you try with the mobile app on your phone?

**Comment by PeterCloet** [comment]
Michael,
Sorry for the late response.
I'm assuming your request to try it with the mobile app was to figure out if it was a general issue related to an addblocker (see #117)? As a test, I bypassed my PiHole this morning and now the stream is playing. 
So, my problems seem to be related to the same cause as for issue #117.
I will close this thread.
