### ISSUE TITLE
Plugin not working in Kodi 20.0

### ISSUE THREAD

**Issue by wardwygaerts** [add-ons/plugin.video.viervijfzes#122]
Today, I updated to Kodi v20.0 and the GoPlay plugin stopped working:

`2023-03-13 23:16:22.381 T:1034     info <general>: CAddonMgr::FindAddons: plugin.video.viervijfzes v0.4.10+matrix.1 installed`

`2023-03-13 23:16:35.264 T:1070    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 5] Input/output error
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/service_entry.py", line 6, in <module>
                                                       from resources.lib import service
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 12, in <module>
                                                       from resources.lib.viervijfzes.auth import AuthApi
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/auth.py", line 12, in <module>
                                                       from resources.lib.viervijfzes.aws.cognito_identity import CognitoIdentity
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/aws/cognito_identity.py", line 9, in <module>
                                                       import requests
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 45, in <module>
                                                       from .exceptions import RequestsDependencyWarning
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/exceptions.py", line 11, in <module>
                                                       from .compat import JSONDecodeError as CompatJSONDecodeError
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/compat.py", line 12, in <module>
                                                       import chardet
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/__init__.py", line 19, in <module>
                                                       from .universaldetector import UniversalDetector
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/universaldetector.py", line 47, in <module>
                                                       from .mbcsgroupprober import MBCSGroupProber
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/mbcsgroupprober.py", line 34, in <module>
                                                       from .gb2312prober import GB2312Prober
                                                     File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 936, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 1073, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 1131, in get_data
                                                   OSError: [Errno 5] Input/output error
                                                   -->End of Python script error report<--`

`2023-03-13 23:16:35.677 T:1090    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 5] Input/output error
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 197, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 122, in show_mylist
                                                       from resources.lib.modules.catalog import Catalog
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/catalog.py", line 10, in <module>
                                                       from resources.lib.modules.menu import Menu
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/menu.py", line 11, in <module>
                                                       from resources.lib.viervijfzes.content import Episode, Program
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 14, in <module>
                                                       import requests
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 45, in <module>
                                                       from .exceptions import RequestsDependencyWarning
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/exceptions.py", line 11, in <module>
                                                       from .compat import JSONDecodeError as CompatJSONDecodeError
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/compat.py", line 12, in <module>
                                                       import chardet
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/__init__.py", line 19, in <module>
                                                       from .universaldetector import UniversalDetector
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/universaldetector.py", line 47, in <module>
                                                       from .mbcsgroupprober import MBCSGroupProber
                                                     File "/storage/.kodi/addons/script.module.chardet/lib/chardet/mbcsgroupprober.py", line 34, in <module>
                                                       from .gb2312prober import GB2312Prober
                                                     File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 936, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 1073, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 1131, in get_data
                                                   OSError: [Errno 5] Input/output error
                                                   -->End of Python script error report<--`
                                                   
`2023-03-13 23:16:35.772 T:1058    error <general>: GetDirectory - Error getting plugin://plugin.video.viervijfzes/mylist`

**Comment by wardwygaerts** [comment]
After uninstalling the add-on, reinstalling, updating pi bootloader and rebooting, the add-on is working again...
