### ISSUE TITLE
GoPlay stream not playing

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.viervijfzes#125]
**Describe the bug**
Stream on Play6 will not start playing

**To Reproduce**
1. Select any stream on GoPlay
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
2023-07-15 20:45:06.510 T:16117    INFO <general>: initializing python engine.
2023-07-15 20:45:06.536 T:16117   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: malformed node or string: False
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 197, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 170, in play_catalog
                                                       Player().play(uuid, literal_eval(islongform))
                                                     File "/usr/lib/python3.8/ast.py", line 99, in literal_eval
                                                     File "/usr/lib/python3.8/ast.py", line 98, in _convert
                                                     File "/usr/lib/python3.8/ast.py", line 75, in _convert_signed_num
                                                     File "/usr/lib/python3.8/ast.py", line 66, in _convert_num
                                                     File "/usr/lib/python3.8/ast.py", line 63, in _raise_malformed_node
                                                   ValueError: malformed node or string: False
                                                   -->End of Python script error report<--

**System**
 - Addon version: 0.4.10
 - Kodi version: 19.4
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreElec
 - Special Hardware (RPI / Vero4K+ / ...): RPI4

**Additional context**

**Comment by PeterCloet** [comment]
Nevermind. This doesn't seem to be an actual issue. Apparantly, I tried to stream a (very bad, come to think of it) movie from Play6 (Exploding Sun). This morning, I get an error stating "this video is not playable" so I suppose that yesterday that was the same issue. It would have been nice to get the same error message instead of a error in the log file.
Issue closed.
