### ISSUE TITLE
Playback fails

### ISSUE THREAD

**Issue by M0nty99** [add-ons/plugin.video.viervijfzes#141]
**Describe the bug**
Trying to playback content from GoPlay

**To Reproduce**
1.Launch content
2.
3.

**Expected behavior**
Content plays

**Logs**
2024-07-06 09:23:18.835 T:1004    debug <CAddonSettings[0@plugin.video.viervijfzes]>: trying to load setting definitions from old format...
2024-07-06 09:23:18.835 T:1004    debug <CSettingsManager>: requested setting (credentials_hash) was not found.

**System**
 - Addon version: 0.4.1.1
 - Kodi version: V21
 - Inputstream adaptive version:0.6.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Librelec
 - Special Hardware (RPI / Vero4K+ / ...): X86 nuc with intel N200

**Additional context**
I've uninstalled the addon, installed again. deleted credentials, entered again multiple times. Tried the credentials in the browser, but keep getting this message.
Somehow it's not reading the credential file it seems.

**Comment by PeterCloet** [comment]
Same here. I tried going to "MyList" in the plugin and immediately got an error.
Seems like an authentication error.
Running LibreElec 11.0.6 (Kodi 20.3.0), Plugin 0.4.11.

`2024-07-06 13:35:52.795 T:1633    error <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] {"message":"Not Found"}
2024-07-06 13:35:52.806 T:1633     info <general>: Skipped 1 duplicate messages..
2024-07-06 13:35:52.806 T:1633    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 197, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 123, in show_mylist
                                                       Catalog().show_mylist()
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/catalog.py", line 254, in show_mylist
                                                       mylist = self._api.get_mylist()
                                                                ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 520, in get_mylist
                                                       data = self._get_url(self.API_GOPLAY + '/my-list', authentication='Bearer %s' % self._auth.get_token())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 784, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
                                                   -->End of Python script error report<--
                                                   
2024-07-06 13:35:52.856 T:1635    error <general>: GetDirectory - Error getting plugin://plugin.video.viervijfzes/mylist
2024-07-06 13:35:52.859 T:1107    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viervijfzes/mylist) failed`

**Comment by frankdpGH** [comment]
Looks like API has changed. TV guide (addon or IPTVmanager) no longer working on Nexus/Omega and Android/windows systems.
Selected search of a program is working on android (after relogin on their website, android app was updated on 31/5/2024).

2024-07-07 12:17:51.552 T:21220    info <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] Starting new HTTPS connection (1): www.goplay.be:443
2024-07-07 12:17:51.738 T:21220    info <general>: Skipped 1 duplicate messages..
2024-07-07 12:17:51.738 T:21220    info <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] https://www.goplay.be:443 "GET /api/epg/vier/2024-07-04 HTTP/1.1" 404 None
2024-07-07 12:17:51.747 T:23502   error <general>: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.viervijfzes: Something went wrong in plugin.video.viervijfzes
2024-07-07 12:17:51.795 T:21220   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: Could not fetch data
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 197, in run
                                                       routing.run(params)
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 191, in iptv_epg
                                                       IPTVManager(int(routing.args['port'][0])).send_epg()  # pylint: disable=too-many-function-args
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/iptvmanager.py", line 33, in send
                                                       sock.sendall(json.dumps(func()).encode())  # pylint: disable=not-callable
                                                                               ^^^^^^
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/iptvmanager.py", line 78, in send_epg
                                                       epg = epg_api.get_epg(key, date.strftime('%Y-%m-%d'))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/epg.py", line 109, in get_epg
                                                       response = self._get_url(self.EPG_ENDPOINTS.get(channel).format(date=date))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Kodi/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/epg.py", line 187, in _get_url
                                                       raise Exception('Could not fetch data')
                                                   Exception: Could not fetch data
                                                   -->End of Python script error report<--

**Comment by blowk** [comment]
Maybe you could find some info on https://github.com/retrospect-addon/plugin.video.retrospect/issues/1809 or https://github.com/retrospect-addon/plugin.video.retrospect/commit/4d6264455182f3c9db2642b11179abba6904ac19 ?

**Comment by PeterCloet** [comment]
The restrospect add-on is an alternative but not really a true replacement for the actual GoPlay app. Some streams are missing, the bitstreams seems to be lower and I also couldn't find back my favourite list(s). So, workaround yes, but longterm solution maybe.
I sure hope someone will still take a look at the issues on this app (GoPlay) causing it no longer to work.
In the past Michael already hinted that he would no longer support this app. Maybe someone else can pick up the torch?

Log with specific error: https://paste.kodi.tv/fosiluvafi.kodi

**Comment by M0nty99** [comment]
Would be great if somebody with coding knowledge and some free time could assist/take over this app form @michaelarnauts
This app has always been working like a charm and replacing our tv-subscription :-)

**Comment by PeterCloet** [comment]
@mediaminister 
I believe you already helped out in the past to "fix" the GoPlay plug-in.
Would you be willing to have a look?

**Comment by PeterCloet** [comment]
@michaelarnauts 
As the new TV season is gearing up... could you please have a look at getting this plug-in working again?

**Comment by M0nty99** [comment]
I'm affraid it's looking grim for the future of this plug-in at the moment. Maybe if @michaelarnauts could make an announcement on the frontpage of the github to ask for assistance to take over his role on this great project. Would be very much appreciated, I understand that as life goes on thing changes. But it would be a shame to let his great work go extinct because no one can/wants to take over his role :-(

**Comment by michaelarnauts** [comment]
I think the time where our Flemish TV Add-ons worked nicely have passed. Content providers have more strict DRM requirements nowdays, and those aren't supported in Kodi.

See https://github.com/add-ons/plugin.video.viervijfzes/pull/129 for example, but also https://github.com/add-ons/plugin.video.tvvlaanderen/issues/63. The VTM Go addon also had issues with some programs IIRC.

Those add-ons also originated from a time when the Chromecast with Google TV didn't exist yet, and there was no way to watch TV comfortably with a remote without having an expensive Telenet/Proximus TV subscription. By now, every channel has an Android TV app that work better then how it worked in Kodi before, and is free of charge.

It has been fun, but I'm afraid this is where it will end...

**Comment by Clyde72** [comment]
> I think the time where our Flemish TV Add-ons worked nicely have passed. Content providers have more strict DRM requirements nowdays, and those aren't supported in Kodi.
> 
> See #129 for example, but also [add-ons/plugin.video.tvvlaanderen#63](https://github.com/add-ons/plugin.video.tvvlaanderen/issues/63). The VTM Go addon also had issues with some programs IIRC.
> 
> Those add-ons also originated from a time when the Chromecast with Google TV didn't exist yet, and there was no way to watch TV comfortably with a remote without having an expensive Telenet/Proximus TV subscription. By now, every channel has an Android TV app that work better then how it worked in Kodi before, and is free of charge.
> 
> It has been fun, but I'm afraid this is where it will end...

I've also allready made that reflexion. In fact since the latest VTM Go addon issue. Kodi served me personally well but it is time to look into other streaming solutions. Looking into mini pc or such to watch VRT, Go Play & VTM via browser over tv or get me an Google Chromecast or get me an Android box.

Things evolve. Thanks for all your good work @michaelarnauts, gave me years of pleasure.

**Comment by M0nty99** [comment]
Thanks for chiming in, unfortunately we have an LG tv which doesn't support the GoPlay addon natively. For us Kodi was the on-stop shop for watching TV or movies. But I get the point you are making @michaelarnauts, I guess it's time for me to look for an alternative solution for watching TV. As having an alternative solution for just one add-on wouldn't pass the WAF ;-).

Thanks for all your time on this add-on, you will be remembered :-)

**Comment by henk31** [comment]
Since yesterday there is a working version again: https://github.com/add-ons/plugin.video.goplay

**Comment by PeterCloet** [comment]
Super news!
I just installed the new plugin and it is working great!
@mediaminister Thanks a lot!

**Comment by M0nty99** [comment]
@mediaminister  Thanks a lot!
