### ISSUE TITLE
Bug: error when starting Kodi

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.viervijfzes#51]
I'm getting error warnings when starting Kodi regarding this addon.
For me everything is working perfect so this is certainly nothing urgent.

Logs mention this ->
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'list' object has no attribute 'get'
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.viervijfzes/service_entry.py", line 8, in <module>
service.run()
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 182, in run
BackgroundService().run()
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 37, in run
self._update_metadata()
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 78, in _update_metadata
success = Metadata().fetch_metadata(callback=update_status)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/metadata.py", line 42, in fetch_metadata
items.extend(self._api.get_programs(channel, CACHE_PREVENT))
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 216, in get_programs
program = self.get_program(channel, path, cache=CACHE_ONLY)  # Get program details, but from cache only
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 262, in get_program
program = self._parse_program_data(data)
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 514, in _parse_program_data
for episode in playlist['episodes']
File "/storage/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 542, in _parse_episode_data
program_title=data.get('program', {}).get('title'),
AttributeError: 'list' object has no attribute 'get'
-->End of Python script error report<--

**Comment by michaelarnauts** [comment]
Vreemd. Kan je wat meer van de log geven, en debug log activeren in de settings?

Heb je ook de laatste code van github gebruikt?

**Comment by vermope** [comment]
@michaelarnauts after updating from latest git the error is gone. Thanks!

**Comment by dagwieers** [comment]
This was fixed by #45
