### ISSUE TITLE
Failing start video

### ISSUE THREAD

**Issue by JeanPoll** [add-ons/plugin.video.viervijfzes#77]
```
2021-02-16 20:44:27.060 T:1915982768  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.viervijfzes/play/page/video%2Fuefa-champions-league%2Fuefa-champions-league-2018-2019%2Flive-fc-barcelona-psg
2021-02-16 20:44:27.062 T:1188004064  NOTICE: Creating InputStream
2021-02-16 20:44:27.063 T:1188004064   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2021-02-16 20:44:27.063 T:1188004064   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.viervijfzes/play/page/video%2Fuefa-champions-league%2Fuefa-champions-league-2018-2019%2Flive-fc-barcelona-psg]
2021-02-16 20:44:27.063 T:1188004064  NOTICE: CVideoPlayer::OnExit()
2021-02-16 20:44:27.123 T:1215279328   ERROR: EXCEPTION: XBMC is not playing any file
2021-02-16 20:44:27.124 T:1215279328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any file
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 120, in onPlayBackStarted
                                                self.stream_path = self.getPlayingFile()
                                            RuntimeError: XBMC is not playing any file
                                            -->End of Python script error report<--
2021-02-16 20:44:27.270 T:1915982768  NOTICE: CVideoPlayer::CloseFile()
2021-02-16 20:44:27.270 T:1915982768  NOTICE: VideoPlayer: waiting for threads to exit
2021-02-16 20:44:27.270 T:1915982768  NOTICE: VideoPlayer: finished waiting
2021-02-16 20:44:27.332 T:1215279328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.MissingSchema'>
                                            Error Contents: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.viervijfzes/resources/lib/service.py", line 167, in onPlayBackStopped
                                                response = requests.get(self.stream_path)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 387, in prepare_url
                                                raise MissingSchema(error)
                                            MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
                                            -->End of Python script error report<--
```

My setup:
Running Kodi
RPi3

**Comment by michaelarnauts** [comment]
Can you try with the latest code in the master branch? I just tried on Android and it is working fine there.

**Comment by JeanPoll** [comment]
Just tried master, same issue here

**Comment by JeanPoll** [comment]
Solved by reboot.

**Comment by dagwieers** [comment]
May be related to https://github.com/xbmc/inputstream.adaptive/issues/454
