### ISSUE TITLE
goPlay werkt niet meer

### ISSUE THREAD

**Issue by doglover3920** [add-ons/plugin.video.viervijfzes#92]
De add-on goPlay blijkt niet meer te werken.
Krijg de foutmelding: GoPlay error.

In de log zie ik dat de credentials niet juist zouden zijn.
Heb deze dan maar opnieuw ingevoerd. Geen resultaat:

Ik gebruik Kodi 19 Matrix op een Linux PC
Add-on updatet tot de laatste wat beschikbaar is.
Fout is dezezefde op een Kodi 18.9 Leia

```
2021-09-15 14:06:39.471 T:2480    DEBUG <general>: StartScript - calling plugin GoPlay('plugin://plugin.video.viervijfzes/channels/Play4/catalog','4','','resume:false')
2021-09-15 14:06:39.471 T:2480    DEBUG <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 7 for script /home/willy/.kodi/addons/plugin.video.viervijfzes/addon_entry.py
2021-09-15 14:06:39.471 T:2438     INFO <general>: initializing python engine.
2021-09-15 14:06:39.472 T:2438    DEBUG <general>: CPythonInvoker(7, /home/willy/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): start processing
2021-09-15 14:06:39.472 T:2438    DEBUG <general>: CPythonInvoker(7, /home/willy/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): entering source directory /home/willy/.kodi/addons/plugin.video.viervijfzes
2021-09-15 14:06:39.472 T:2438    DEBUG <general>: CPythonInvoker(7, /home/willy/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): instantiating addon using automatically obtained id of "plugin.video.viervijfzes" dependent on version 3.0.0 of the xbmc.python api
2021-09-15 14:06:39.474 T:2438    DEBUG <general>: [plugin.video.viervijfzes][routing] Dispatching to 'show_channel_catalog', args: {'channel': 'Play4'}
2021-09-15 14:06:39.481 T:2438    DEBUG <CAddonSettings[plugin.video.viervijfzes]>: trying to load setting definitions from old format...
2021-09-15 14:06:39.481 T:2438    DEBUG <CSettingsManager>: requested setting (credentials_hash) was not found.
2021-09-15 14:06:39.484 T:2438    DEBUG <CAddonSettings[plugin.video.viervijfzes]>: trying to load setting definitions from old format...
2021-09-15 14:06:39.484 T:2438    DEBUG <CSettingsManager>: requested setting (credentials_hash) was not found.
2021-09-15 14:06:39.484 T:2438    DEBUG <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Fetching programs.json from cache
2021-09-15 14:06:39.488 T:2438    ERROR <general>: Skipped 2 duplicate messages..
2021-09-15 14:06:39.488 T:2438    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'description'
                                                   Traceback (most recent call last):
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 194, in run
                                                       routing.run(params)
                                                     File "/home/willy/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/willy/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/addon.py", line 60, in show_channel_catalog
                                                       Catalog().show_catalog_channel(channel)
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/modules/catalog.py", line 47, in show_catalog_channel
                                                       items = self._api.get_programs(channel)
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 217, in get_programs
                                                       self._parse_program_data(record) for record in data if record['pageInfo']['brand'] == channel
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 217, in <listcomp>
                                                       self._parse_program_data(record) for record in data if record['pageInfo']['brand'] == channel
                                                     File "/home/willy/.kodi/addons/plugin.video.viervijfzes/resources/lib/viervijfzes/content.py", line 602, in _parse_program_data
                                                       description=html_to_kodi(data['description']),
                                                   KeyError: 'description'
                                                   -->End of Python script error report<--
```

**Comment by mediaminister** [comment]
Kan je volgende update eens uittesten?
Voor Kodi 18: [plugin.video.viervijfzes-0.4.3-fixmenu-7654ffa.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7170262/plugin.video.viervijfzes-0.4.3-fixmenu-7654ffa.zip)
Voort Kodi 19: [plugin.video.viervijfzes-0.4.3+matrix.1-fixmenu-7654ffa.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7170263/plugin.video.viervijfzes-0.4.3%2Bmatrix.1-fixmenu-7654ffa.zip)

**Comment by doglover3920** [comment]
Werkt als een trein...  voor beide versies.
Tenminste ikheb niet langer dan 30 seconden laten spelen.

**Comment by mediaminister** [comment]
Recommendations menu werkt nog niet.
